# Generated by Django 5.0.6 on 2024-06-13 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie_blog_model',
            old_name='Movie_Trailer',
            new_name='Movie_Trailer_link',
        ),
    ]
