# Generated by Django 5.0.6 on 2024-06-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0002_rename_movie_trailer_movie_blog_model_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_blog_model',
            name='Movie_Trailer_link',
            field=models.URLField(),
        ),
    ]
