# Generated by Django 5.0.6 on 2024-06-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0003_alter_movie_blog_model_movie_trailer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=20)),
                ('Comment', models.TextField()),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Comment_date', models.DateTimeField(auto_now=True)),
                ('Movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_movie.movie_blog_model')),
            ],
        ),
    ]
