# Generated by Django 5.0.6 on 2024-06-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0004_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_blog_model',
            name='Movie_Trailer_link',
            field=models.CharField(max_length=1000),
        ),
    ]
