# Generated by Django 5.0.6 on 2024-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movie', '0005_alter_movie_blog_model_movie_trailer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_blog_model',
            name='Movie_Title',
            field=models.CharField(max_length=50),
        ),
    ]
